en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} KILAV GROUP FREEDOM NETWORKS ASSOCIATION. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "KIGENA"
  params:
    description: "Homepage KIGENA Website"
    ### accessibility ###
    #accessibility:
    #  skip_text: "Skip to content"
    #  help_text: "Accessibility Statement"
    #  help_url: "/help/"
    ### calls to action ###
    main_cta:
      text: "Support us"
      link: "/support-us/"
    footer_cta:
      text: "Support us"
      link: "/support-us/"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: "about-1"
      name: "About KIGENA"
      url: "/about/kigena/"
      weight: 1
      post: "What is KIGENA?"
      parent: "about"
    - identifier: "about-2"
      name: "People"
      url: "/about/people/"
      weight: 2
      post: "Who is KIGENA?"
      parent: "about"
    - identifier: "about-3"
      name: "Inspector General"
      url: "/about/inspgen/"
      weight: 3
      post: "KIGENA Inspector General"
      parent: "about"
    - identifier: "demo-page"
      name: "Our projects"
      url: "/projects/"
      weight: 2
    - identifier: "community"
      name: "Community"
      url: "/community/"
      weight: 3
    - identifier: "news"
      name: "News"
      url: "/news/"
      weight: 4
